# -*- coding: utf-8 -*-
"""Mock Matplotlib

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uhTCxsuVwFP8-qncyoEYCC2v_2a1Uiyl

# Problem:
Imagine you are working for a travel agency named "Wanderlust Adventures." Your team has been assigned a project to analyze and visualize the travel data for the past year. The data includes information about various destinations, the number of travelers per month, and the revenue generated. As the data analyst, you decide to use Matplotlib to create insightful visualizations. <br>
As a data analyst at "Wanderlust Adventures," you have been given a dataset containing monthly travel data for different destinations. The dataset includes information about the number of travelers and the revenue generated each month. Your task is to create three visualizations using Matplotlib: a line plot, a pie chart, and a scatter plot.

1.   <strong>Line Plot: </strong> Create a line plot using Matplotlib that illustrates the trend of both traveler count and revenue over the past year. The x-axis should represent the months, while the y-axis should represent the traveler count and revenue, respectively. The line plot should display two lines, one for traveler count and another for revenue, showcasing their trends over time.
2.   <strong>Pie Chart: </strong> Generate a pie chart using Matplotlib to display the distribution of traveler count among the top five destinations for the entire year. Each slice of the pie should represent a destination, and its size should correspond to the proportion of travelers visiting that particular destination.
3.  <strong>Scatter Plot: </strong> Create a scatter plot using Matplotlib that demonstrates the relationship between the number of travelers and the revenue generated for each month. Each data point on the scatter plot should represent a month, with the x-coordinate representing the traveler count and the y-coordinate representing the revenue generated.

<strong>Note:</strong> Use the file called "travel.csv"
"""

#Please use the file travel.csv for the above
#The dataset is available at https://tinyurl.com/travelDataset
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

df = pd.read_csv("sample_data/travel.csv")

df

df1 = df.groupby("Month").agg({'Travelers':'sum', 'Revenue':'sum'}).reset_index()

monthdf = pd.DataFrame({'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun','Jul', 'Aug', 'Sep', 'Oct', 'Nov', "Dec"], 'value' : [x for x in range(0,12)]})
monthdf
df1 = pd.merge(df1, monthdf, on = ['Month'], how = 'inner').sort_values(by = ['value'], ascending = True)

df1

# df1['Month']= pd.to_datetime(df['Month'])
# df1

df1['Revenue'] = df1['Revenue']/100



"""### Plot 1"""

plt.plot(df1['Month'], df1['Travelers'], label = 'Travelers', color = 'blue', marker = '^')
plt.plot(df1['Month'], df1['Revenue'], label = 'Revenue in 100$', color = 'red', marker = 'o')
plt.xlabel("Month")
plt.ylabel("Count")
plt.legend()
plt.title("traveler count and revenue over the past year")
plt.show()

"""### Plot 2"""

df.head(2)

df2 = df.groupby("Destination").agg({'Travelers':'sum', 'Revenue':'sum'}).reset_index()

df2.head(2)

df2 = df2.sort_values(by = ['Travelers'], ascending = False).head()
df2

prop = [int(x) for x in df2['Travelers']/df2['Travelers'].sum()* 100]
prop

[f'{x}%' for x in prop]

def lablef(x):
  return f'{x}%'

# help(plt.pie)

plt.pie(df2['Travelers'], labels = df2['Destination'], autopct = lambda x: f'{np.round(x,1)}%')
plt.title("Travellers by Destination in last year")
plt.show()

"""# Plot 3"""

df1

plt.scatter(df1['Travelers'], df1['Revenue'], c = np.random.rand(12), cmap = 'viridis', s = 50)
for i in range(0,len(df1)):
    plt.annotate(df1['Month'][i], (df1['Travelers'][i], df1['Revenue'][i]), textcoords="offset points", xytext=(0, 10), ha='center')
plt.xlabel("Travelers Count")
plt.ylabel("Revenue Generated")
plt.title("Traveler Count vs Revenue Generated for each month")
plt.show()

